name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Sync to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./
          protocol: ftps
          port: 21

      - name: Purge Cloudflare Cache
        run: |
          RESPONSE=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"hosts":["actuary.blakehugh.es"]}')
          echo "Cloudflare Response: $RESPONSE"
          if [[ "$RESPONSE" != *'"success":true'* ]]; then
            echo "Cloudflare purge failed!"
            exit 1
          fi
